#!/usr/bin/env python3
"""Train a sparse-root octree model from a sparse_octree_pairs.npz cache."""

import argparse
from pathlib import Path

from voxel_tree.utils.progress import report as _report_progress

try:
    from voxel_tree.tasks.sparse_octree.sparse_octree_train import train_sparse_octree
except ModuleNotFoundError:
    # Ensure all relevant package roots are importable.
    # The repo layout is:
    #   <repo-root>/VoxelTree/          (contains the `VoxelTree` package directory)
    #   <repo-root>/LODiffusion/        (contains the `LODiffusion` package directory)
    import sys

    script_path = Path(__file__).resolve()
    repo_root = script_path.parents[4]  # .../MC/ (workspace root)
    voxel_tree_pkg_root = script_path.parents[3]  # .../VoxelTree/ (repo root)

    for p in (voxel_tree_pkg_root, repo_root):
        if str(p) not in sys.path:
            sys.path.insert(0, str(p))

    from voxel_tree.tasks.sparse_octree.sparse_octree_train import train_sparse_octree


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Train a sparse-root octree model from a sparse_octree_pairs.npz cache."
    )
    parser.add_argument(
        "--data",
        type=Path,
        required=True,
        help="Path to sparse_octree_pairs.npz (generated by build_octree_pairs --sparse-root).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("sparse_octree_model.pt"),
        help="Output checkpoint file.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=20,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Batch size.",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate.",
    )
    parser.add_argument(
        "--split-weight",
        type=float,
        default=1.0,
        help="Global lambda for split BCE loss.",
    )
    parser.add_argument(
        "--label-weight",
        type=float,
        default=0.35,
        help="Global lambda for leaf-only material CE loss.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Torch device (cpu/cuda).",
    )
    parser.add_argument(
        "--num-classes",
        type=int,
        default=513,
        help=(
            "Number of block classes for the label head. "
            "Must match the reduced vocabulary size (513). "
            "See voxel_tree/config/voxy_vocab.json."
        ),
    )
    parser.add_argument(
        "--hidden",
        type=int,
        default=72,
        help="Hidden size for the sparse-root model.",
    )
    parser.add_argument(
        "--model-variant",
        type=str,
        default="fast",
        choices=("fast", "baseline"),
        help="Sparse-root model variant to train.",
    )
    parser.add_argument(
        "--pruning-boost",
        type=float,
        default=4.0,
        help="Extra loss multiplier for geometrically-prunable nodes (Phase 5). 0 to disable.",
    )
    parser.add_argument(
        "--resume",
        type=Path,
        default=None,
        help="Path to a checkpoint to resume training from. Epochs is the total target.",
    )
    parser.add_argument(
        "--no-cache-targets",
        action="store_true",
        default=False,
        help="Disable target caching to reduce memory usage for large datasets.",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=None,
        help="Limit training to first N samples (for quick e2e validation).",
    )
    args = parser.parse_args(argv)

    def _progress(epoch, total, metrics):
        _report_progress(epoch, total)
        prune_str = ""
        if "prune_agree_rate" in metrics:
            prune_str = f" prune_agree={metrics['prune_agree_rate']:.4f}"
        print(
            f"[{epoch}/{total}] "
            f"loss={metrics['loss']:.6f} "
            f"split_f1={metrics['split_f1']:.4f} "
            f"leaf_acc={metrics['leaf_acc']:.4f} "
            f"leaf_ratio={metrics['leaf_node_ratio']:.3f}"
            f"{prune_str}"
        )

    result = train_sparse_octree(
        data_path=args.data,
        out_path=args.out,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        split_weight=args.split_weight,
        label_weight=args.label_weight,
        hidden=args.hidden,
        device=args.device,
        num_classes=args.num_classes,
        model_variant=args.model_variant,
        pruning_boost=args.pruning_boost,
        resume_from=args.resume,
        cache_targets=not args.no_cache_targets,
        max_samples=args.max_samples,
        progress_callback=_progress,
    )

    print("Training complete")
    print(result)


if __name__ == "__main__":
    main()
