package com.voxeltree.harvester.ingest;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.core.SectionPos;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.permissions.Permissions;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LightLayer;
import net.minecraft.world.level.chunk.DataLayer;
import net.minecraft.world.level.chunk.LevelChunk;
import net.minecraft.world.level.chunk.LevelChunkSection;
import net.minecraft.world.level.storage.LevelResource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.RandomAccessFile;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Stream;

/**
 * Server-side command that iterates over pre-generated region files and
 * sends each chunk to connected clients for Voxy ingestion.
 *
 * <p>The serialisation format mirrors VoxyWorldGen v2's
 * {@code broadcastLODData()} exactly: each section's
 * {@code PalettedContainer<BlockState>}, biome palette, and light data
 * are written to a {@link IngestPayload} packet. The client-side handler
 * reconstructs the sections and calls Voxy's
 * {@code VoxelIngestService.rawIngest()} via reflection — identical
 * code path to normal VoxyWorldGen gameplay.
 *
 * <h3>Usage</h3>
 * <pre>
 * /ingestall              — ingest all chunks in every region file
 * /ingestall 256          — ingest chunks within 256-chunk radius of player
 * /ingestall stop         — cancel an ongoing ingest
 * /ingestall status       — show progress
 * </pre>
 *
 * <p>Processing is spread across server ticks with a configurable time
 * budget ({@value #TICK_BUDGET_MS}ms) so TPS remains acceptable. Chunks
 * are loaded from disk synchronously (pre-generated by Chunky/vanilla),
 * serialised, sent, and then left for the server's chunk manager to
 * unload normally.
 */
public class IngestAllCommand {

    private static final Logger LOGGER = LoggerFactory.getLogger("dataharvester");

    /** Max milliseconds spent loading/sending chunks per server tick. */
    private static final long TICK_BUDGET_MS = 25;

    // ---- active operation state (null when idle) ----
    private static Deque<ChunkPos> queue;
    private static ServerLevel activeLevel;
    private static CommandSourceStack activeSource;
    private static int totalChunks;
    private static int processedChunks;
    private static int skippedChunks;
    private static int errorChunks;
    private static long startTimeMs;
    private static boolean tickListenerRegistered;

    /**
     * Register the {@code /ingestall} command tree.  Should be called
     * from {@link com.voxeltree.harvester.DataHarvesterMod}.
     */
    public static void register(CommandDispatcher<CommandSourceStack> dispatcher) {
        dispatcher.register(Commands.literal("ingestall")
                .requires(src -> src.permissions()
                        .hasPermission(Permissions.COMMANDS_GAMEMASTER))
                .executes(ctx -> startIngest(ctx.getSource(), -1))
                .then(Commands.literal("stop")
                        .executes(ctx -> stopIngest(ctx.getSource())))
                .then(Commands.literal("status")
                        .executes(ctx -> showStatus(ctx.getSource())))
                .then(Commands.argument("radius", IntegerArgumentType.integer(1, 4096))
                        .executes(ctx -> startIngest(ctx.getSource(),
                                IntegerArgumentType.getInteger(ctx, "radius")))));
    }

    // ==================== command handlers ====================

    private static int startIngest(CommandSourceStack source, int radiusChunks) {
        if (queue != null) {
            source.sendFailure(Component.literal(
                    "Ingest already running (" + processedChunks + "/" + totalChunks
                    + "). Use /ingestall stop first."));
            return 0;
        }

        ServerLevel level = source.getLevel();
        ChunkPos center = new ChunkPos(
                (int) source.getPosition().x >> 4,
                (int) source.getPosition().z >> 4);

        // 1. Scan region files for existing chunk positions
        List<ChunkPos> chunks;
        try {
            chunks = scanRegionFiles(level, center, radiusChunks);
        } catch (Exception e) {
            source.sendFailure(Component.literal(
                    "Failed to scan region files: " + e.getMessage()));
            LOGGER.error("[DataHarvester] Region scan failed", e);
            return 0;
        }

        if (chunks.isEmpty()) {
            source.sendFailure(Component.literal("No chunks found in region files."));
            return 0;
        }

        // 2. Sort by distance from center (closest first — matches Voxy spiral)
        chunks.sort(Comparator.comparingLong(pos -> {
            long dx = (long) pos.x - center.x;
            long dz = (long) pos.z - center.z;
            return dx * dx + dz * dz;
        }));

        // 3. Initialise state
        queue = new ArrayDeque<>(chunks);
        activeLevel = level;
        activeSource = source;
        totalChunks = chunks.size();
        processedChunks = 0;
        skippedChunks = 0;
        errorChunks = 0;
        startTimeMs = System.currentTimeMillis();

        // 4. Register tick listener (idempotent — never unregistered)
        if (!tickListenerRegistered) {
            ServerTickEvents.END_SERVER_TICK.register(IngestAllCommand::onServerTick);
            tickListenerRegistered = true;
        }

        String scopeDesc = radiusChunks > 0
                ? String.format(" within %d-chunk radius of (%.0f, %.0f)",
                        radiusChunks, source.getPosition().x, source.getPosition().z)
                : " from all region files";
        source.sendSuccess(() -> Component.literal(
                String.format("Starting ingest of %,d chunks%s", totalChunks, scopeDesc)), true);
        LOGGER.info("[DataHarvester] /ingestall: {} chunks queued{}", totalChunks, scopeDesc);
        return 1;
    }

    private static int stopIngest(CommandSourceStack source) {
        if (queue == null) {
            source.sendFailure(Component.literal("No ingest running."));
            return 0;
        }
        String msg = formatProgress("Stopped");
        source.sendSuccess(() -> Component.literal(msg), true);
        LOGGER.info("[DataHarvester] {}", msg);
        resetState();
        return 1;
    }

    private static int showStatus(CommandSourceStack source) {
        if (queue == null) {
            source.sendSuccess(() -> Component.literal("No ingest running."), false);
            return 1;
        }
        String msg = formatProgress("In progress");
        source.sendSuccess(() -> Component.literal(msg), false);
        return 1;
    }

    // ==================== tick processing ====================

    private static void onServerTick(MinecraftServer server) {
        Deque<ChunkPos> q = queue;
        ServerLevel level = activeLevel;
        if (q == null || level == null) return;

        // Check completion
        if (q.isEmpty()) {
            String msg = formatProgress("Complete");
            LOGGER.info("[DataHarvester] {}", msg);
            if (activeSource != null) {
                try {
                    activeSource.sendSuccess(() -> Component.literal(msg), true);
                } catch (Exception ignored) { /* source may have disconnected */ }
            }
            resetState();
            return;
        }

        // Need at least one client in the same dimension to receive data
        List<ServerPlayer> receivers = server.getPlayerList().getPlayers().stream()
                .filter(p -> p.level() == level)
                .filter(p -> ServerPlayNetworking.canSend(p, IngestPayload.TYPE))
                .toList();
        if (receivers.isEmpty()) return;

        // Process chunks within the time budget
        long deadlineNanos = System.nanoTime() + TICK_BUDGET_MS * 1_000_000L;
        int batchCount = 0;

        while (!q.isEmpty() && System.nanoTime() < deadlineNanos) {
            ChunkPos pos = q.poll();
            try {
                // Synchronous load — fast for pre-generated chunks on disk
                LevelChunk chunk = level.getChunk(pos.x, pos.z);
                if (chunk.isEmpty()) {
                    skippedChunks++;
                    continue;
                }

                IngestPayload payload = serializeChunk(chunk);
                if (payload == null) {
                    skippedChunks++;
                    continue;
                }

                for (ServerPlayer player : receivers) {
                    ServerPlayNetworking.send(player, payload);
                }
                processedChunks++;
                batchCount++;

            } catch (Exception e) {
                errorChunks++;
                if (errorChunks <= 10) {
                    LOGGER.warn("[DataHarvester] Chunk ({}, {}) failed: {}",
                            pos.x, pos.z, e.getMessage());
                } else if (errorChunks == 11) {
                    LOGGER.warn("[DataHarvester] Suppressing further error details.");
                }
            }
        }

        // Periodic progress log (roughly every 500 chunks)
        if (batchCount > 0 && processedChunks % 500 < batchCount) {
            LOGGER.info("[DataHarvester] {}", formatProgress("Progress"));
        }
    }

    // ==================== chunk serialisation ====================

    /**
     * Serialise a loaded {@link LevelChunk} into an {@link IngestPayload}.
     *
     * <p>This mirrors VoxyWorldGen v2's {@code NetworkHandler.broadcastLODData()}
     * line-for-line: for each non-air section, the block-state palette, biome
     * palette, and light layers are written to byte arrays using Minecraft's
     * native {@code PalettedContainer.write()} and {@code DataLayer.getData()}.
     *
     * @return the payload, or {@code null} if the chunk has no non-air sections
     */
    private static IngestPayload serializeChunk(LevelChunk chunk) {
        int minY = chunk.getMinSectionY();
        List<IngestPayload.SectionData> sections = new ArrayList<>();
        var lightEngine = chunk.getLevel().getLightEngine();

        for (int i = 0; i < chunk.getSections().length; i++) {
            LevelChunkSection section = chunk.getSections()[i];
            if (section == null || section.hasOnlyAir()) continue;

            // Serialise PalettedContainer<BlockState> and biomes to byte[]
            io.netty.buffer.ByteBuf statesRaw = io.netty.buffer.Unpooled.buffer();
            io.netty.buffer.ByteBuf biomesRaw = io.netty.buffer.Unpooled.buffer();
            byte[] states, biomes;
            try {
                RegistryFriendlyByteBuf statesBuf = new RegistryFriendlyByteBuf(
                        new FriendlyByteBuf(statesRaw), chunk.getLevel().registryAccess());
                section.getStates().write(statesBuf);
                states = new byte[statesBuf.readableBytes()];
                statesBuf.readBytes(states);

                RegistryFriendlyByteBuf biomesBuf = new RegistryFriendlyByteBuf(
                        new FriendlyByteBuf(biomesRaw), chunk.getLevel().registryAccess());
                section.getBiomes().write(biomesBuf);
                biomes = new byte[biomesBuf.readableBytes()];
                biomesBuf.readBytes(biomes);
            } finally {
                statesRaw.release();
                biomesRaw.release();
            }

            // Light data (may be null for sections that haven't been lit)
            SectionPos sectionPos = SectionPos.of(chunk.getPos(), minY + i);
            DataLayer bl = lightEngine.getLayerListener(LightLayer.BLOCK)
                    .getDataLayerData(sectionPos);
            DataLayer sl = lightEngine.getLayerListener(LightLayer.SKY)
                    .getDataLayerData(sectionPos);

            sections.add(new IngestPayload.SectionData(
                    minY + i,
                    states,
                    biomes,
                    bl != null ? bl.getData().clone() : null,
                    sl != null ? sl.getData().clone() : null));
        }

        return sections.isEmpty() ? null
                : new IngestPayload(chunk.getPos(), minY, sections);
    }

    // ==================== region file scanning ====================

    /**
     * Scan {@code .mca} region file headers to discover all chunk positions
     * that have data on disk, optionally filtered to within {@code radiusChunks}
     * of {@code center}.
     *
     * <p>Each {@code .mca} file has a 4 KiB header (1024 × 4-byte entries).
     * A non-zero entry means that chunk exists in the file.
     *
     * @param radiusChunks max chunk distance, or -1 for all
     */
    static List<ChunkPos> scanRegionFiles(ServerLevel level, ChunkPos center,
                                          int radiusChunks) throws Exception {
        Path regionDir = getRegionDir(level);
        if (!Files.isDirectory(regionDir)) {
            throw new IllegalStateException("Region directory not found: " + regionDir);
        }

        long radiusSq = radiusChunks > 0
                ? (long) radiusChunks * radiusChunks : Long.MAX_VALUE;
        List<ChunkPos> result = new ArrayList<>();

        try (Stream<Path> files = Files.list(regionDir)) {
            for (Path regionFile : files
                    .filter(p -> p.toString().endsWith(".mca")).toList()) {
                String name = regionFile.getFileName().toString();
                // Format: r.<regionX>.<regionZ>.mca
                String inner = name.substring(2, name.length() - 4); // strip "r." and ".mca"
                String[] parts = inner.split("\\.");
                if (parts.length != 2) continue;

                int regionX, regionZ;
                try {
                    regionX = Integer.parseInt(parts[0]);
                    regionZ = Integer.parseInt(parts[1]);
                } catch (NumberFormatException e) {
                    continue;
                }

                // Read 4 KiB header — 1024 entries of 4 bytes (offset << 8 | sectorCount)
                try (RandomAccessFile raf = new RandomAccessFile(
                        regionFile.toFile(), "r")) {
                    if (raf.length() < 4096) continue;

                    for (int localZ = 0; localZ < 32; localZ++) {
                        for (int localX = 0; localX < 32; localX++) {
                            raf.seek(4L * (localX + localZ * 32));
                            int value = raf.readInt();
                            if (value == 0) continue; // chunk not present

                            int cx = regionX * 32 + localX;
                            int cz = regionZ * 32 + localZ;

                            // Distance filter
                            long dx = cx - center.x;
                            long dz = cz - center.z;
                            if (dx * dx + dz * dz <= radiusSq) {
                                result.add(new ChunkPos(cx, cz));
                            }
                        }
                    }
                }
            }
        }

        return result;
    }

    /**
     * Resolve the region directory for the given dimension.
     *
     * <p>Standard layout:
     * <ul>
     *   <li>Overworld: {@code <world>/region/}</li>
     *   <li>Nether:    {@code <world>/DIM-1/region/}</li>
     *   <li>End:       {@code <world>/DIM1/region/}</li>
     *   <li>Custom:    {@code <world>/dimensions/<ns>/<path>/region/}</li>
     * </ul>
     */
    private static Path getRegionDir(ServerLevel level) {
        // getWorldPath resolves relative to the world save root
        Path worldDir = level.getServer()
                .getWorldPath(LevelResource.LEVEL_DATA_FILE).getParent();
        ResourceKey<Level> dim = level.dimension();

        if (dim.equals(Level.OVERWORLD)) {
            return worldDir.resolve("region");
        } else if (dim.equals(Level.NETHER)) {
            return worldDir.resolve("DIM-1").resolve("region");
        } else if (dim.equals(Level.END)) {
            return worldDir.resolve("DIM1").resolve("region");
        } else {
            return worldDir.resolve("dimensions")
                    .resolve(dim.identifier().getNamespace())
                    .resolve(dim.identifier().getPath())
                    .resolve("region");
        }
    }

    // ==================== helpers ====================

    private static void resetState() {
        queue = null;
        activeLevel = null;
        activeSource = null;
    }

    private static String formatProgress(String label) {
        double pct = totalChunks > 0 ? 100.0 * processedChunks / totalChunks : 0;
        long elapsed = System.currentTimeMillis() - startTimeMs;
        double cps = elapsed > 0 ? 1000.0 * processedChunks / elapsed : 0;
        int remaining = queue != null ? queue.size() : 0;
        double etaMin = cps > 0 ? remaining / cps / 60.0 : 0;
        return String.format(
                "%s: %,d / %,d (%.1f%%) — %,d skipped, %,d errors — "
                + "%.0f chunks/s — ETA %.1f min",
                label, processedChunks, totalChunks, pct,
                skippedChunks, errorChunks, cps, etaMin);
    }
}
