package com.rhythmatician.voxygen.backend.voxy;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.function.Consumer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Exposes Voxy's chunk processing pipeline as a programmatic API.
 *
 * <p>Allows the dataset generation system to request on-demand chunk processing without requiring
 * a player to be nearby. Instead of relying on chunk load events, this API provides:
 * <ul>
 *   <li>{@link #processChunk(int, int)} - Process a chunk at specific coordinates</li>
 *   <li>{@link #registerSectionCaptureListener(Consumer)} - Hook into VoxelizedSection data before
 *       insertion into Voxy's cache</li>
 * </ul>
 *
 * <p><b>Usage Pattern:</b>
 * <pre>
 * // Register callback
 * VoxyProcessingAPI.registerSectionCaptureListener(section -> {
 *     exportSectionToDataset(section);
 * });
 *
 * // Request chunk processing
 * VoxyProcessingAPI.processChunk(100, 200);
 * </pre>
 *
 * <p><b>Design Notes:</b>
 * <ul>
 *   <li>This is a client-side API; chunks must be loaded on the client (e.g., via Chunky)</li>
 *   <li>The section capture callback is invoked <b>after mipping</b> but <b>before Voxy's storage</b>
 *       to obtain raw voxelized data</li>
 *   <li>Processing is asynchronous; Voxy's ingest service handles the actual work on its worker
 *       thread</li>
 * </ul>
 */
public final class VoxyProcessingAPI {
    private static final Logger LOGGER = LoggerFactory.getLogger(VoxyProcessingAPI.class);

    /**
     * Listeners for VoxelizedSection data capture. These are called with the VoxelizedSection
     * object after mipping but before insertion into Voxy's world engine.
     *
     * <p>The listener receives a {@code VoxelizedSectionSnapshot} which is a copy/snapshot of the
     * data suitable for export.
     */
    private static final ConcurrentLinkedDeque<Consumer<VoxelizedSectionSnapshot>> SECTION_LISTENERS = new ConcurrentLinkedDeque<>();

    private VoxyProcessingAPI() {}

    /**
     * Register a listener to receive VoxelizedSection data after mipping.
     *
     * <p>The snapshot is captured at the point where Voxy has completed mipping (LOD level
     * generation) but before the section is inserted into the world engine. This ensures you
     * capture the complete multi-level LOD data in its pre-compressed form.
     *
     * @param listener Consumer that receives VoxelizedSectionSnapshot objects
     */
    public static void registerSectionCaptureListener(
            Consumer<VoxelizedSectionSnapshot> listener) {
        SECTION_LISTENERS.add(listener);
        LOGGER.debug("Registered section capture listener. Total listeners: {}", SECTION_LISTENERS.size());
    }

    /**
     * Unregister a previously registered listener.
     *
     * @param listener The listener to remove
     */
    public static void unregisterSectionCaptureListener(
            Consumer<VoxelizedSectionSnapshot> listener) {
        SECTION_LISTENERS.remove(listener);
        LOGGER.debug("Unregistered section capture listener. Remaining listeners: {}", SECTION_LISTENERS.size());
    }

    /**
     * Clear all registered listeners.
     */
    public static void clearSectionCaptureListeners() {
        SECTION_LISTENERS.clear();
    }

    /**
     * Get the count of active listeners.
     *
     * @return Number of registered listeners
     */
    public static int getListenerCount() {
        return SECTION_LISTENERS.size();
    }

    /**
     * Fire section capture callbacks. Called internally by the mixin after mipping.
     *
     * @param snapshot The VoxelizedSectionSnapshot to pass to listeners
     */
    public static void fireCaptureSectionCallbacks(VoxelizedSectionSnapshot snapshot) {
        for (Consumer<VoxelizedSectionSnapshot> listener : SECTION_LISTENERS) {
            try {
                listener.accept(snapshot);
            } catch (Exception e) {
                LOGGER.warn("Exception in section capture listener", e);
            }
        }
    }

    /**
     * Process a chunk at the given coordinates on-demand, without requiring a player nearby.
     *
     * <p>The chunk must already be loaded on the client (e.g., pre-generated by Chunky). This
     * method:
     * <ol>
     *   <li>Retrieves the LevelChunk from the client chunk cache</li>
     *   <li>Enqueues it with Voxy's VoxelIngestService for processing</li>
     *   <li>Returns immediately (processing is asynchronous)</li>
     * </ol>
     *
     * @param chunkX The chunk X coordinate
     * @param chunkZ The chunk Z coordinate
     * @return true if the chunk was successfully enqueued, false if the chunk is not loaded or
     *         Voxy is unavailable
     */
    public static boolean processChunk(int chunkX, int chunkZ) {
        if (!VoxyDetection.isAvailable()) {
            LOGGER.warn("Voxy is not available; cannot process chunk ({}, {})", chunkX, chunkZ);
            return false;
        }

        try {
            Class<?> minecraftClass = Class.forName("net.minecraft.client.Minecraft");
            Method getInstance = minecraftClass.getMethod("getInstance");
            Object mc = getInstance.invoke(null);
            if (mc == null) {
                LOGGER.warn("No Minecraft instance available; cannot process chunk ({}, {})", chunkX, chunkZ);
                return false;
            }

            Object level = getField(mc, "level", "world");
            if (level == null) {
                LOGGER.warn("No world loaded; cannot process chunk ({}, {})", chunkX, chunkZ);
                return false;
            }

            Object chunk = getChunkFromLevel(level, chunkX, chunkZ);
            if (chunk == null) {
                LOGGER.debug("Chunk ({}, {}) not loaded in client cache", chunkX, chunkZ);
                return false;
            }

            // Try to ingest the chunk using Voxy's static API
            return tryIngestChunkViaReflection(chunk, chunkX, chunkZ);
        } catch (ClassNotFoundException e) {
            LOGGER.warn("Minecraft client classes not found; must be running in a client environment", e);
            return false;
        } catch (Exception e) {
            LOGGER.warn("Error processing chunk ({}, {})", chunkX, chunkZ, e);
            return false;
        }
    }

    private static Object getField(Object obj, String... names) {
        if (obj == null) {
            return null;
        }

        Class<?> cls = obj.getClass();
        for (String name : names) {
            try {
                Field field = cls.getDeclaredField(name);
                field.setAccessible(true);
                return field.get(obj);
            } catch (NoSuchFieldException | IllegalAccessException ignored) {
                // Try next name
            }
        }
        // Search in superclass hierarchy
        Class<?> superClass = cls.getSuperclass();
        while (superClass != null) {
            for (String name : names) {
                try {
                    Field field = superClass.getDeclaredField(name);
                    field.setAccessible(true);
                    return field.get(obj);
                } catch (NoSuchFieldException | IllegalAccessException ignored) {
                    // Try next name
                }
            }
            superClass = superClass.getSuperclass();
        }
        return null;
    }

    private static Object getChunkFromLevel(Object level, int chunkX, int chunkZ) {
        if (level == null) {
            return null;
        }

        Class<?> cls = level.getClass();
        // Try common method signatures for getting a loaded chunk
        for (Method method : cls.getMethods()) {
            if (!method.getName().equals("getChunk")) {
                continue;
            }
            Class<?>[] params = method.getParameterTypes();
            try {
                if (params.length == 2 && params[0] == int.class && params[1] == int.class) {
                    return method.invoke(level, chunkX, chunkZ);
                }
                if (params.length == 3 && params[0] == int.class && params[1] == int.class && params[2] == boolean.class) {
                    // avoid creating chunks if we can
                    return method.invoke(level, chunkX, chunkZ, false);
                }
            } catch (Exception ignored) {
                // ignore and try other overloads
            }
        }

        // Fallback: try method names that differ across MC versions
        for (String candidate : new String[]{"getChunkAt", "getLoadedChunk"}) {
            try {
                Method method = cls.getMethod(candidate, int.class, int.class);
                return method.invoke(level, chunkX, chunkZ);
            } catch (Exception ignored) {
                // ignore
            }
        }

        return null;
    }

    /**
     * Attempt to ingest a chunk via Voxy's public API using reflection.
     *
     * <p>Uses {@code VoxelIngestService.tryAutoIngestChunk(LevelChunk)} to properly route the
     * chunk to the correct world engine based on the chunk's level.
     *
     * @param chunk The chunk to ingest
     * @param chunkX The chunk X coordinate (for logging)
     * @param chunkZ The chunk Z coordinate (for logging)
     * @return true if ingestion was successful or enqueued, false otherwise
     */
    private static boolean tryIngestChunkViaReflection(Object chunk, int chunkX, int chunkZ) {
        try {
            // Load the VoxelIngestService class via reflection
            Class<?> voxelIngestServiceClass =
                    Class.forName("me.cortex.voxy.common.world.service.VoxelIngestService");

            Method tryAutoIngestMethod = null;
            for (Method method : voxelIngestServiceClass.getMethods()) {
                if (!method.getName().equals("tryAutoIngestChunk")) {
                    continue;
                }
                Class<?>[] params = method.getParameterTypes();
                if (params.length == 1) {
                    tryAutoIngestMethod = method;
                    break;
                }
            }

            if (tryAutoIngestMethod == null) {
                LOGGER.warn("VoxelIngestService.tryAutoIngestChunk method not found");
                return false;
            }

            // Call VoxelIngestService.tryAutoIngestChunk(chunk)
            Boolean result = (Boolean) tryAutoIngestMethod.invoke(null, chunk);
            if (Boolean.TRUE.equals(result)) {
                LOGGER.debug("Chunk ({}, {}) enqueued for processing", chunkX, chunkZ);
            } else {
                LOGGER.debug("Chunk ({}, {}) was not enqueued (possibly invalid or no valid world)",
                        chunkX, chunkZ);
            }
            return result;
        } catch (ClassNotFoundException e) {
            LOGGER.warn("VoxelIngestService class not found; Voxy may not be installed", e);
            return false;
        } catch (Exception e) {
            LOGGER.warn("Error invoking VoxelIngestService.tryAutoIngestChunk", e);
            return false;
        }
    }
}
