#!/usr/bin/env python3
"""Train a sparse-root octree model from a sparse_root_pairs.npz cache."""

import argparse
from pathlib import Path

try:
    from VoxelTree.core.sparse_root_train import train_sparse_root
except ModuleNotFoundError:
    # Ensure all relevant package roots are importable.
    # The repo layout is:
    #   <repo-root>/VoxelTree/          (contains the `VoxelTree` package directory)
    #   <repo-root>/LODiffusion/        (contains the `LODiffusion` package directory)
    import sys

    script_path = Path(__file__).resolve()
    repo_root = script_path.parents[2]  # <repo-root>
    voxel_tree_pkg_root = script_path.parents[1]  # <repo-root>/VoxelTree

    for p in (voxel_tree_pkg_root, repo_root):
        if str(p) not in sys.path:
            sys.path.insert(0, str(p))

    from VoxelTree.core.sparse_root_train import train_sparse_root


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Train a sparse-root octree model from a sparse_root_pairs.npz cache."
    )
    parser.add_argument(
        "--data",
        type=Path,
        required=True,
        help="Path to sparse_root_pairs.npz (generated by build_octree_pairs --sparse-root).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("sparse_root_model.pt"),
        help="Output checkpoint file.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=20,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Batch size.",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate.",
    )
    parser.add_argument(
        "--split-weight",
        type=float,
        default=1.0,
        help="Global lambda for split BCE loss.",
    )
    parser.add_argument(
        "--label-weight",
        type=float,
        default=0.35,
        help="Global lambda for leaf-only material CE loss.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Torch device (cpu/cuda).",
    )
    parser.add_argument(
        "--num-classes",
        type=int,
        default=1104,
        help=(
            "Number of block classes for the label head. "
            "Must match the project-wide Voxy block vocabulary size (1104). "
            "See VoxelTree/README.md and VoxelTree/VoxelTree/train/octree_models.py "
            "(block_vocab_size = 1104)."
        ),
    )
    parser.add_argument(
        "--hidden",
        type=int,
        default=72,
        help="Hidden size for the sparse-root model.",
    )
    parser.add_argument(
        "--model-variant",
        type=str,
        default="fast",
        choices=("fast", "baseline"),
        help="Sparse-root model variant to train.",
    )
    args = parser.parse_args(argv)

    def _progress(epoch, total, metrics):
        print(
            f"[{epoch}/{total}] "
            f"loss={metrics['loss']:.6f} "
            f"split_f1={metrics['split_f1']:.4f} "
            f"leaf_acc={metrics['leaf_acc']:.4f} "
            f"leaf_ratio={metrics['leaf_node_ratio']:.3f}"
        )

    result = train_sparse_root(
        data_path=args.data,
        out_path=args.out,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        split_weight=args.split_weight,
        label_weight=args.label_weight,
        hidden=args.hidden,
        device=args.device,
        num_classes=args.num_classes,
        model_variant=args.model_variant,
        progress_callback=_progress,
    )

    print("Training complete")
    print(result)


if __name__ == "__main__":
    main()
