"""GUI node for training the sparse-root octree model."""

from pathlib import Path

from VoxelTree.core.sparse_root_train import train_sparse_root


class SparseRootTrainNode:
    """GUI node that trains a sparse-root octree model.

    Prerequisites:
        - A sparse_root_pairs.npz cache generated by:
              python scripts/build_octree_pairs.py --sparse-root
    """

    # For GUI node wiring / graph display
    prerequisites = ["build_octree_pairs --sparse-root"]

    def __init__(self, gui_context):
        self.gui_context = gui_context
        self.progress_bar = gui_context.get_circular_progress_bar()

        # Defaults (can be overridden via configure)
        self.data_path = None
        self.output_path = None
        self.epochs = 20
        self.batch_size = 16
        self.lr = 1e-3
        self.device = "cpu"
        self.num_classes = 256

    def configure(
        self,
        data_path: Path,
        output_path: Path,
        epochs: int = 20,
        batch_size: int = 16,
        lr: float = 1e-3,
        device: str = "cpu",
        num_classes: int = 256,
    ):
        self.data_path = data_path
        self.output_path = output_path
        self.epochs = epochs
        self.batch_size = batch_size
        self.lr = lr
        self.device = device
        self.num_classes = num_classes

    def run(self):
        self.progress_bar.set_value(0.0)
        self.progress_bar.set_text("Starting sparse-root training...")

        def progress_callback(epoch, total, metrics):
            self.progress_bar.set_value(epoch / total)
            self.progress_bar.set_text(f"Epoch {epoch}/{total} | loss={metrics['loss']:.5f}")

        assert self.data_path is not None, "data_path must be configured"
        assert self.output_path is not None, "output_path must be configured"

        result = train_sparse_root(
            data_path=self.data_path,
            out_path=self.output_path,
            epochs=self.epochs,
            batch_size=self.batch_size,
            lr=self.lr,
            device=self.device,
            num_classes=self.num_classes,
            progress_callback=progress_callback,
        )

        self.progress_bar.set_value(1.0)
        self.progress_bar.set_text("Sparse-root training complete.")
        self.gui_context.notify_training_complete(result)
