#!/usr/bin/env bash
set -euo pipefail
# Reconstruct tools/server-harness/runtime/ from pinned manifests.
# Verifies sha256 where provided; fails closed on mismatch.

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
HARNESS="$ROOT/tools/server-harness"
RUNTIME="$HARNESS/runtime"
MANIFEST_MODS="$HARNESS/mods.manifest.json"
MANIFEST_SERVER="$HARNESS/server.manifest.json"

mkdir -p "$RUNTIME/mods" "$RUNTIME/versions/1.21.11" "$RUNTIME/config"

echo "[server-harness] Copying tracked config -> runtime/config/"
cp -r "$HARNESS/config/"* "$RUNTIME/config/" 2>/dev/null || cp -r "$HARNESS/config" "$RUNTIME/"

# Helper: download with curl and verify sha256
fetch_and_verify() {
  local url="$1" dest="$2" expected_sha="$3"
  if [[ -f "$dest" ]]; then
    echo "[server-harness] verifying existing $dest"
    echo "$expected_sha  $dest" | sha256sum --check --strict
    return 0
  fi
  echo "[server-harness] downloading $url -> $dest"
  mkdir -p "$(dirname "$dest")"
  if ! curl -L --fail --retry 3 -o "$dest" "$url"; then
    echo "[server-harness] WARNING: download failed for $url (offline? manual fetch required)" >&2
    echo "[server-harness] expected sha256 $expected_sha for $dest" >&2
    rm -f "$dest"
    return 1
  fi
  echo "$expected_sha  $dest" | sha256sum --check --strict
}

# Server launcher jar (generated by Fabric installer; may be rebuilt via installer if download fails)
LAUNCHER_SHA=$(jq -r .launcherJar.sha256 "$MANIFEST_SERVER")
LAUNCHER_FILE=$(jq -r .launcherJar.file "$MANIFEST_SERVER")
LAUNCHER_DEST="$HARNESS/$LAUNCHER_FILE"
# Launcher jar lives at harness root (sibling to runtime), historically fabric-server-mc.*.jar
if [[ ! -f "$HARNESS/$LAUNCHER_FILE" ]]; then
  echo "[server-harness] launcher jar not found at $HARNESS/$LAUNCHER_FILE"
  echo "[server-harness] To generate: java -jar fabric-installer.jar server -mcversion 1.21.11 -loader 0.18.4 -downloadMinecraft"
  echo "[server-harness] Fabric installer: https://maven.fabricmc.net/net/fabricmc/fabric-installer/"
fi
# Also ensure copy exists in legacy location for tooling that expects harness root
if [[ -f "$HARNESS/$LAUNCHER_FILE" ]]; then
  echo "$LAUNCHER_SHA  $HARNESS/$LAUNCHER_FILE" | sha256sum --check --strict
fi

# Vanilla server jar
VANILLA_SHA=$(jq -r .vanillaServerJar.sha256 "$MANIFEST_SERVER")
VANILLA_URL=$(jq -r .vanillaServerJar.url "$MANIFEST_SERVER")
VANILLA_DEST="$RUNTIME/versions/1.21.11/server-1.21.11.jar"
fetch_and_verify "$VANILLA_URL" "$VANILLA_DEST" "$VANILLA_SHA" || echo "[server-harness] vanilla server jar missing — fetch manually or via Fabric installer" >&2

# Mods
for i in $(jq -r '.mods | keys | .[]' "$MANIFEST_MODS"); do
  file=$(jq -r ".mods[$i].file" "$MANIFEST_MODS")
  sha=$(jq -r ".mods[$i].sha256" "$MANIFEST_MODS")
  url=$(jq -r ".mods[$i].url" "$MANIFEST_MODS")
  dest="$RUNTIME/mods/$file"
  fetch_and_verify "$url" "$dest" "$sha" || echo "[server-harness] mod $file missing — download from $url and verify sha256 $sha" >&2
done

echo "[server-harness] runtime reconstructed at $RUNTIME (built jars still need local gradle builds)"
echo "[server-harness] built artifacts (if needed):"
echo "  tools/data-harvester/gradlew -p tools/data-harvester build  -> $RUNTIME/mods/"
echo "  ./java/gradlew -p java build  -> $RUNTIME/mods/"
