"""
convert_noise_dumps_to_npz.py
------------------------------
Converts real Minecraft noise dump JSON files generated by the LODiffusion
Fabric mod (/dumpnoise command) into a canonical NPZ file for density NN training.

Each JSON chunk file contains:
  - continents, erosion, ridges, depth, temperature, vegetation : 16 floats each
    These are sampled at cell-column centres (4x4 per chunk, indexed cx*4+cz),
    and do NOT vary with Y in Minecraft's noise router.
  - final_density : 768 floats (4x48x4 per chunk, indexed cx*192+cy*4+cz)
    This IS the real Minecraft density function output at every cell.

Model input features (7 channels, shape per chunk: 4x48x4x7):
  0  continents    - broadcast from 4x4 surface to 4x48x4
  1  erosion       - broadcast
  2  ridges        - broadcast
  3  depth         - broadcast
  4  temperature   - broadcast
  5  vegetation    - broadcast
  6  y_norm        - normalised cell-centre Y coordinate, unique per Y level

Model output (1 channel, shape per chunk: 4x48x4x1):
  0  final_density - real Minecraft density, positive = solid, negative = air

By default this script produces cell-level training data (4x48x4). With
--subchunk it will instead emit per-subchunk data (24×16x16x16 per chunk).

Output arrays saved to noise_training_data/terrain_shaper_density_data.npz:
  inputs  : (N, 4, 48, 4, 7)   float32
  outputs : (N, 4, 48, 4, 1)   float32
"""

import argparse
import json
import multiprocessing as mp
import random
import sys
from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Coordinate constants (matches Minecraft 1.20.x noise grid)
# ---------------------------------------------------------------------------
CX_CELLS = 4  # cells per chunk in X
CY_CELLS = 48  # cells per chunk in Y  (world height 384 / cell height 8)
CZ_CELLS = 4  # cells per chunk in Z

# Y centre of each cell layer: -64 + cy*8 + 4
Y_MIN = -64.0 + 0 * 8 + 4  # cy=0  → -60
Y_MAX = -64.0 + 47 * 8 + 4  # cy=47 → 316

SURFACE_FEATURES = [
    "continents",
    "erosion",
    "ridges",
    "depth",
    "temperature",
    "vegetation",
]
INPUT_CHANNELS = len(SURFACE_FEATURES) + 1  # +1 for y_norm
OUTPUT_CHANNELS = 1

# Whether to emit per-16×16×16 subchunk training examples.
# Controlled by --subchunk in the CLI.
SUBCHUNK_MODE = False


def y_norm_channel():
    """Return the normalised Y-coord tensor (48,) broadcast-ready."""
    raw = np.array([-64.0 + cy * 8 + 4 for cy in range(CY_CELLS)], dtype=np.float32)
    return (raw - Y_MIN) / (Y_MAX - Y_MIN) * 2.0 - 1.0  # → [-1, +1]


def trilinear_upsample_cell_grid_to_blocks(cell_grid: np.ndarray) -> np.ndarray:
    """Upsample a 4×48×4 cell grid to a 16×384×16 block grid.

    Vanilla Minecraft interpolates the 4×48×4 density grid (cell-centre samples)
    to block resolution (16×384×16) using trilinear interpolation within each
    4×8×4 cell.

    The cell grid is indexed [cx][cy][cz] where:
      - cx in [0..3] corresponds to blocks x in [0..15]
      - cy in [0..47] corresponds to blocks y in [-64..319]
      - cz in [0..3] corresponds to blocks z in [0..15]

    Each cell spans 4×8×4 blocks.
    """
    # cell_grid: (4, 48, 4)
    cell_width = 4
    cell_height = 8

    # output block grid size
    BX, BY, BZ = CX_CELLS * cell_width, CY_CELLS * cell_height, CZ_CELLS * cell_width
    out = np.empty((BX, BY, BZ), dtype=cell_grid.dtype)

    # Precompute clamped indices for the `+1` offsets.
    # This mirrors Minecraft's behaviour which clamps at the chunk boundary.
    def clamp_axis(idx, max_idx):
        return idx if idx < max_idx else max_idx

    for bx in range(BX):
        cx = bx // cell_width
        fx = (bx % cell_width) / cell_width
        cx1 = clamp_axis(cx + 1, CX_CELLS - 1)
        for bz in range(BZ):
            cz = bz // cell_width
            fz = (bz % cell_width) / cell_width
            cz1 = clamp_axis(cz + 1, CZ_CELLS - 1)
            for by in range(BY):
                # by indexes blocks from -64..319 (mapped to 0..383)
                cy = by // cell_height
                fy = (by % cell_height) / cell_height
                cy1 = clamp_axis(cy + 1, CY_CELLS - 1)

                # 8 corner values of the current 4×8×4 cell
                v000 = cell_grid[cx, cy, cz]
                v100 = cell_grid[cx1, cy, cz]
                v010 = cell_grid[cx, cy1, cz]
                v110 = cell_grid[cx1, cy1, cz]
                v001 = cell_grid[cx, cy, cz1]
                v101 = cell_grid[cx1, cy, cz1]
                v011 = cell_grid[cx, cy1, cz1]
                v111 = cell_grid[cx1, cy1, cz1]

                # trilinear interpolation
                x00 = v000 + (v100 - v000) * fx
                x10 = v010 + (v110 - v010) * fx
                x01 = v001 + (v101 - v001) * fx
                x11 = v011 + (v111 - v011) * fx
                y0 = x00 + (x10 - x00) * fy
                y1 = x01 + (x11 - x01) * fy
                out[bx, by, bz] = y0 + (y1 - y0) * fz

    return out


def parse_chunk(data: dict, subchunk_mode: bool = False) -> tuple[np.ndarray, np.ndarray]:
    """Parse one chunk dict.

    If subchunk_mode is False (default), returns:
      inputs:  (4,48,4,7)  (cell resolution)
      outputs: (4,48,4,1)

    If subchunk_mode is True, returns per-subchunk blocks:
      inputs:  (24, 16,16,16,7)
      outputs: (24, 16,16,16,1)
    """
    # --- validate final_density --------------------------------------------------
    fd = data.get("final_density")
    if fd is None or len(fd) != CX_CELLS * CY_CELLS * CZ_CELLS:
        raise ValueError(f"final_density length {len(fd) if fd else 'missing'}")

    # reshape to (4, 48, 4) : index was cx*192 + cy*4 + cz
    density = np.array(fd, dtype=np.float32).reshape(CX_CELLS, CY_CELLS, CZ_CELLS)

    # --- surface features --------------------------------------------------------
    y_norm = y_norm_channel()  # shape (48,)

    surface_tensors = []
    for feat in SURFACE_FEATURES:
        vals = data.get(feat)
        if vals is None or len(vals) != CX_CELLS * CZ_CELLS:
            # Some dump formats may omit surface features (e.g. only final_density.
            # In that case, fall back to zeros so training can still proceed.
            vals = [0.0] * (CX_CELLS * CZ_CELLS)
        # reshape (16,) → (4, 4), then broadcast to (4, 48, 4)
        surf = np.array(vals, dtype=np.float32).reshape(CX_CELLS, CZ_CELLS)
        surf3d = np.tile(surf[:, np.newaxis, :], (1, CY_CELLS, 1))
        surface_tensors.append(surf3d)  # each (4,48,4)

    # y_norm: broadcast (48,) → (4, 48, 4)
    y3d = np.broadcast_to(y_norm[np.newaxis, :, np.newaxis], (CX_CELLS, CY_CELLS, CZ_CELLS)).copy()

    if not subchunk_mode:
        # --- stack → (4, 48, 4, 7) --------------------------------------------------
        all_channels = surface_tensors + [y3d]
        inputs = np.stack(all_channels, axis=-1).astype(np.float32)  # (4,48,4,7)
        outputs = density[..., np.newaxis].astype(np.float32)  # (4,48,4,1)
        return inputs, outputs

    # --- subchunk mode: upsample to block resolution (16×384×16) ---------------
    # surface features: broadcast to blocks by repeating each cell
    block_inputs = []
    for surf3d in surface_tensors:
        surf_block = np.repeat(np.repeat(np.repeat(surf3d, 4, axis=0), 8, axis=1), 4, axis=2)
        block_inputs.append(surf_block)

    # y_norm: per-block (384) -> broadcast to (16,384,16)
    ys = np.linspace(-64.0, 319.0, num=384, dtype=np.float32)
    # Normalize block Y over full world height range (-64..319)
    y_norm_blocks = (ys + 64.0) / (319.0 + 64.0) * 2.0 - 1.0
    y_block = np.broadcast_to(y_norm_blocks[np.newaxis, :, np.newaxis], (16, 384, 16)).astype(
        np.float32
    )
    block_inputs.append(y_block)

    # final density: trilinear interpolation from cell grid
    density_block = trilinear_upsample_cell_grid_to_blocks(density)

    # stack features: (16,384,16,7)
    inputs_block = np.stack(block_inputs, axis=-1)

    # slice into 24 subchunks along Y
    sub_inputs = []
    sub_outputs = []
    for s in range(24):
        y0 = s * 16
        y1 = y0 + 16
        sub_inputs.append(inputs_block[:, y0:y1, :, :])
        sub_outputs.append(density_block[:, y0:y1, :][:, :, :, np.newaxis])

    inputs_arr = np.stack(sub_inputs, axis=0)
    outputs_arr = np.stack(sub_outputs, axis=0)
    return inputs_arr, outputs_arr


def _worker(args_tuple):
    """Top-level worker for multiprocessing (must be picklable)."""
    fp_str, subchunk_mode = args_tuple
    fp = Path(fp_str)
    try:
        with fp.open() as fh:
            data = json.load(fh)
        inp, out = parse_chunk(data, subchunk_mode=subchunk_mode)
        return inp, out, None
    except Exception as exc:
        return None, None, f"{fp.name}: {exc}"


def main():
    ap = argparse.ArgumentParser(description="Convert LODiffusion noise dumps → NPZ")
    ap.add_argument(
        "--dump-dir",
        default=r"VoxelTree\tools\fabric-server\runtime\terrain_shaper_dumps",
        help="Directory containing terrain_shaper chunk_*.json files",
    )
    ap.add_argument(
        "--out",
        default=r"noise_training_data\terrain_shaper_density_data.npz",
        help="Output .npz path",
    )
    ap.add_argument(
        "--max-chunks",
        type=int,
        default=20_000,
        help="Cap on chunks to process (0 = all)",
    )
    ap.add_argument(
        "--seed",
        type=int,
        default=42,
        help="RNG seed for chunk shuffling",
    )
    ap.add_argument(
        "--workers",
        type=int,
        default=min(8, mp.cpu_count()),
        help="Parallel worker processes",
    )
    ap.add_argument(
        "--subchunk",
        action="store_true",
        help="Emit per-subchunk (16x16x16) training examples (24 per chunk).",
    )
    args = ap.parse_args()

    global SUBCHUNK_MODE
    SUBCHUNK_MODE = args.subchunk

    repo_root = Path(__file__).resolve().parents[1]
    dump_dir = repo_root / args.dump_dir
    out_path = repo_root / args.out

    if not dump_dir.is_dir():
        sys.exit(f"ERROR: dump directory not found:\n  {dump_dir}")

    json_files = sorted(dump_dir.glob("chunk_*.json"))
    if not json_files:
        sys.exit(f"ERROR: no chunk_*.json files in {dump_dir}")

    print(f"Found {len(json_files):,} chunk JSON files in {dump_dir}")

    # optionally cap & shuffle
    limit = args.max_chunks if args.max_chunks > 0 else len(json_files)
    if len(json_files) > limit:
        rng = random.Random(args.seed)
        json_files = rng.sample(json_files, limit)
        print(f"Randomly sampled {limit:,} chunks (seed={args.seed})")

    file_strs = [(str(fp), args.subchunk) for fp in json_files]
    print(f"Parsing with {args.workers} workers …")

    # --- parallel parse ---------------------------------------------------------
    inputs_list = []
    outputs_list = []
    skipped = 0
    reported = 0

    with mp.Pool(processes=args.workers) as pool:
        for i, (inp, out, err) in enumerate(
            pool.imap_unordered(_worker, file_strs, chunksize=50), 1
        ):
            if err is not None:
                skipped += 1
                if skipped <= 5:
                    print(f"  SKIP {err}")
            else:
                inputs_list.append(inp)
                outputs_list.append(out)
            if i - reported >= 2000:
                reported = i
                print(f"  processed {i:,}/{len(json_files):,} …")

    n = len(inputs_list)
    if n == 0:
        sys.exit("ERROR: no valid chunks parsed.")

    print(f"\nParsed {n:,} chunks  ({skipped} skipped)")

    inputs = np.stack(inputs_list, axis=0)
    outputs = np.stack(outputs_list, axis=0)

    print(f"inputs  shape : {inputs.shape}   dtype={inputs.dtype}")
    print(f"outputs shape : {outputs.shape}  dtype={outputs.dtype}")

    # --- quick stats ------------------------------------------------------------
    # Collapse to a single vector for summary stats
    flat_out = outputs.reshape(-1)
    print("\nfinal_density stats:")
    print(
        f"  min={flat_out.min():.4f}  max={flat_out.max():.4f}"
        f"  mean={flat_out.mean():.4f}  std={flat_out.std():.4f}"
    )
    solid_frac = (flat_out > 0).mean()
    print(f"  solid fraction (density>0): {solid_frac:.3f}")

    # --- save -------------------------------------------------------------------
    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out_path, inputs=inputs, outputs=outputs)
    size_mb = out_path.stat().st_size / 1e6
    print(f"\nSaved → {out_path}  ({size_mb:.1f} MB)")
    if not SUBCHUNK_MODE:
        print("\nFeature channels (axis=-1):")
        for i, name in enumerate(SURFACE_FEATURES):
            print(f"  [{i}] {name}")
        print("  [6] y_norm  (cell-centre Y, normalised to [-1,+1])")
        print("\nYou can now train: SimpleDensityNet(input_channels=7, output_channels=1)")
    else:
        print("\nSubchunk mode: output is per-16×16×16 block subchunk.")


if __name__ == "__main__":
    main()
