graph TD
    A[Build/Deploy LODiffusion without models] --> B

    subgraph PREGEN [Data Generation & Preprocessing]
        B[Launch Fabric Server with dedicated settings] --> C[Apply /tick freeze]
        B --> D[Run /dumpnoise]
        C --> E[Run chunky world gen]
        E --> F[Run /voxy import world]
        F --> G[Shut down Fabric Server]
        D --> G
        G --> H[Add column heights]
        H --> I[Build training pairs]
    end

    subgraph TRAINING [Model Training & Deployment]
        I --> J[Train]
        J --> K[Export]
        K --> L[Deploy]
    end

    %% Loopback Logic
    J --> M[Delete all training data]
    M --> N[Pick new world seed]
    N --> B