package com.rhythmatician.lodiffusion.gpu;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL30;
import org.lwjgl.opengl.GL43;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;

/**
 * Manages two OpenGL SSBOs for GPU biome classification:
 *
 * <ul>
 *   <li><b>Binding 12 — BiomePalette (static)</b>: The full overworld biome parameter table
 *       generated by {@link BiomePaletteSerializer}. Uploaded once at world load and kept for
 *       the session lifetime.</li>
 *   <li><b>Binding 13 — BiomeOutput (dynamic)</b>: Output buffer written by the compute shader
 *       during each chunk dispatch. Contains one {@code int} per biome lattice point:
 *       4 × 4 × (384/4) = 1536 entries, indexed as
 *       {@code qx * (4 * BIOME_Y_LEVELS) + qz * BIOME_Y_LEVELS + qy}.</li>
 * </ul>
 */
public final class BiomePaletteSSBO implements AutoCloseable {

    private static final Logger LOGGER = LogManager.getLogger();

    /** Binding point for the static biome palette SSBO (must match terrain_compute.comp). */
    public static final int PALETTE_SSBO_BINDING = 12;

    /** Binding point for the per-dispatch biome output SSBO (must match terrain_compute.comp). */
    public static final int OUTPUT_SSBO_BINDING = 13;

    /**
     * Number of ints in the biome output per dispatch:
     * 4 (qx) × 4 (qz) × 96 (qy = Y_LEVELS/4 = 384/4) = 1536.
     */
    public static final int OUTPUT_ENTRY_COUNT = 4 * 4 * 96;

    /** Number of Y quart-positions per full chunk column (Y_LEVELS / 4). */
    public static final int BIOME_Y_LEVELS = 96;

    private int paletteSsboId = -1;
    private int outputSsboId  = -1;

    private final int paletteEntryCount;

    /**
     * Creates both SSBOs from the serialized palette.
     *
     * @param palette     float buffer produced by {@link BiomePaletteSerializer#buildPalette(Object)}.
     *                    Position must be 0, limit = paletteEntryCount * {@link BiomePaletteSerializer#ENTRY_STRIDE}.
     * @param entryCount  number of biome parameter entries in {@code palette}.
     */
    public BiomePaletteSSBO(FloatBuffer palette, int entryCount) {
        this.paletteEntryCount = entryCount;

        int[] ids = new int[2];
        GL15.glGenBuffers(ids);
        paletteSsboId = ids[0];
        outputSsboId  = ids[1];

        // --- Binding 12: static palette ---
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, paletteSsboId);
        GL15.glBufferData(GL43.GL_SHADER_STORAGE_BUFFER, palette, GL15.GL_STATIC_DRAW);

        // --- Binding 13: output buffer (zeroed, dynamic) ---
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, outputSsboId);
        ByteBuffer zeroBuf = ByteBuffer.allocateDirect(OUTPUT_ENTRY_COUNT * Integer.BYTES)
                .order(ByteOrder.nativeOrder());
        GL15.glBufferData(GL43.GL_SHADER_STORAGE_BUFFER, zeroBuf, GL15.GL_DYNAMIC_READ);

        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, 0);

        LOGGER.info("BiomePaletteSSBO: palette={} entries ({} floats), output={} ints",
                entryCount, entryCount * BiomePaletteSerializer.ENTRY_STRIDE, OUTPUT_ENTRY_COUNT);
    }

    /** Returns the number of biome parameter entries in the palette. */
    public int getPaletteEntryCount() {
        return paletteEntryCount;
    }

    /**
     * Binds both SSBOs to their shader binding points.
     * Call this before each compute dispatch.
     */
    public void bind() {
        if (paletteSsboId < 0 || outputSsboId < 0) {
            throw new IllegalStateException("BiomePaletteSSBO not initialized");
        }
        GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, PALETTE_SSBO_BINDING, paletteSsboId);
        GL30.glBindBufferBase(GL43.GL_SHADER_STORAGE_BUFFER, OUTPUT_SSBO_BINDING,  outputSsboId);
    }

    /**
     * Reads back the biome output written by the most recent compute dispatch.
     *
     * <p>Must be called after the dispatch barrier has completed.
     *
     * @return array of {@value #OUTPUT_ENTRY_COUNT} canonical biome IDs (0–53; 255 = unknown),
     *         indexed as {@code qx * (4 * BIOME_Y_LEVELS) + qz * BIOME_Y_LEVELS + qy}.
     */
    public int[] readBiomeOutput() {
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, outputSsboId);
        ByteBuffer raw = GL15.glMapBuffer(GL43.GL_SHADER_STORAGE_BUFFER, GL15.GL_READ_ONLY);
        int[] result = new int[OUTPUT_ENTRY_COUNT];
        if (raw != null) {
            IntBuffer ib = raw.asIntBuffer();
            for (int i = 0; i < OUTPUT_ENTRY_COUNT; i++) {
                result[i] = ib.get(i);
            }
            GL15.glUnmapBuffer(GL43.GL_SHADER_STORAGE_BUFFER);
        } else {
            LOGGER.warn("BiomePaletteSSBO: glMapBuffer returned null for output SSBO");
        }
        GL15.glBindBuffer(GL43.GL_SHADER_STORAGE_BUFFER, 0);
        return result;
    }

    /**
     * Extracts a single 4×4×4 section of biome output starting at Y-quart {@code startQy}.
     *
     * <p>Convenience wrapper for {@link com.rhythmatician.lodiffusion.world.noise.tools.NoiseTap NoiseTap} integration: the NoiseTap biome cache is
     * 4×4×4 ints for a 16-block Y section, with {@code qy} in [0, 3] relative to the section
     * bottom. Pass {@code startQy = (sectionAnchorY - Y_MIN) / 4} to select the right window.
     *
     * @param allBiomes  the full 1536-element array from {@link #readBiomeOutput()}
     * @param startQy    base Y-quart index (0 = chunk bottom, 0..92)
     * @return 4×4×4 biome array indexed [qx][qz][local_qy] where local_qy ∈ [0,3]
     */
    public static int[][][] extractSection(int[] allBiomes, int startQy) {
        int[][][] out = new int[4][4][4];
        for (int qx = 0; qx < 4; qx++) {
            for (int qz = 0; qz < 4; qz++) {
                for (int qyRel = 0; qyRel < 4; qyRel++) {
                    int qy = startQy + qyRel;
                    out[qx][qz][qyRel] = allBiomes[qx * (4 * BIOME_Y_LEVELS) + qz * BIOME_Y_LEVELS + qy];
                }
            }
        }
        return out;
    }

    /** Release GPU resources. */
    public void cleanup() {
        if (paletteSsboId >= 0) {
            GL15.glDeleteBuffers(paletteSsboId);
            paletteSsboId = -1;
        }
        if (outputSsboId >= 0) {
            GL15.glDeleteBuffers(outputSsboId);
            outputSsboId = -1;
        }
    }

    @Override
    public void close() {
        cleanup();
    }
}
